config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'markets#index'
  # get 'theme', to: 'welcome#theme'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_for :admin_users, path: 'admin/profile', format: false, skip: [:registrations]

  resources :markets do
    member do
      get 'cover/*filename' => 'markets#cover', as: 'cover', format: false
    end
    collection do
      get 'watchlist/:list' => 'markets#watchlist', as: 'watchlist'
    end
    resources :market_outcomes, shallow: true
    resources :trading_sets, path: 'sets', shallow: true
  end

  resources :market_outcomes, path: 'outcomes' do
    resources :trading_orders, path: 'orders', shallow: true do
      collection do
        put 'preview'
        get 'help'
      end
    end
  end

  namespace :my do
    resources :funds do
      collection do
        match 'withdraw/:currency' => 'funds#withdraw', as: 'withdraw', via: %w[get post]
        get 'statement/:currency' => 'funds#statement', as: 'statement'
      end
    end

    resources :shares
    resources :trading_orders, path: 'orders'
    resources :trading_sets, path: 'sets'
    resources :referrals
  end

  get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
  get 'market/:id/:title' => 'markets#show', as: 'titled_market'

  get 'blog' => 'blog#index', as: 'blog'
  get 'blog/:id/*title' => 'blog#show', as: 'blog_post'
  post'blog/subscribe' => 'blog#subscribe', as: 'blog_subscribe'

  mount ApplicationApi, at: '/api/'

  admin_constraint = lambda do |request|
    admin = request.env['warden'].user(:admin_user)
    admin.is_a?(AdminUser) && admin.superadmin?
  end

  constraints admin_constraint do
    mount Resque::Server.new, at: '/admin/resque'
    namespace :admin do
      get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
      resources :markets do
        resources :market_outcomes
      end
    end
  end

  %w[about how terms fees security referral].each do |page|
    get page => "pages##{page}", as: page
  end
  get 'bounty' => redirect('/referral')
end

app/controllers/concerns/my/shares_history.rb
module My::SharesHistory
  extend ActiveSupport::Concern

  included do
  end

  protected

    # TODO: move this information into separate table in the databse
    # and run periodic tasks to update the aggregate information
    def order_chart
      @all_orders = @contract.trades.where('created_at > ?', 1.month.ago)
      @orders_chart = { }
      30.times do |i|
        timestamp = (i).days.ago.end_of_day
        # TODO shitty statistics, does not take into account the volume
        filtered_prices = @all_orders.reject { |e| e.created_at.end_of_day != timestamp}.map(&:price)
        @orders_chart[timestamp] = DescriptiveStatistics::Stats.new(filtered_prices)
      end
    end

    def contract_transactions(limit = 25)
      raise "no contract is set" unless @contract
      scope = current_user.contract_transactions.where(contract: @contract).where.not(total_change: 0).order('id desc')
      scope.page(params[:s_page]).per(limit)
    end

    def current_user_objects_init
      return unless current_user
      @trading_orders = trading_orders
      @historical_orders = historical_orders
      @shares_transactions = spendable_shares
    end

  private

    def trading_orders
      current_user.trading_orders.user_actionable.where(market: @market)
    end

    def historical_orders
      current_user.trading_orders.historical.where(market: @market).order('id desc').limit(10)
    end

    def spendable_shares
      current_user.spendable_shares.select { |trx| trx.market == @market }
    end
end

app/controllers/my/funds_controller.rb
class My::FundsController < ApplicationController
  # TODO: remove assign wallets
  # TODO: fail form if corrupt currency
  def index
    current_user.assign_wallets
    @transfers = current_user.currency_transfers.order('id desc').page(params[:page]).per(5)
  end

  def withdraw
    form_init
    if @form.corrupted?
      redirect_to my_funds_path
    elsif request.post? && @form.save
      process_successful_withdrawal
    end
  end

  def statement
    scope = current_user.currency_transactions.where(currency: params['currency'])
    @currency_transactions = scope.where.not(total_change: 0).order('id desc').page(params[:page]).per(25)
  end

  private

    # TODO: add user friendly dialog
    def process_successful_withdrawal
      redirect_to my_funds_path, notice: 'Done, we will process your transfer within 24 hours.'
    end

    def form_init
      @form = WithdrawForm.new(form_params.merge(user: current_user, currency: params[:currency]))
    end

    def form_params
      params.fetch(:withdraw_form, {}).permit(:address, :money, :currency)
    end
end

app/controllers/my/referrals_controller.rb
class My::ReferralsController < ApplicationController
  def index
    @referred_visitors = current_user.referred_visitors.registered
  end
end

app/controllers/my/shares_controller.rb
class My::SharesController < ApplicationController
  include My::SharesHistory
  def index
    @shares = current_user.spendable_shares.group_by(&:market)
  end

  def show
    @contract = Contract.findy(params[:id])
    @contract_transactions = contract_transactions
  end
end

app/controllers/my/trading_orders_controller.rb
class My::TradingOrdersController < ApplicationController
  include My::SharesHistory
  before_action :init_trading_order, only: %i[show destroy]

  def index
    @trading_orders = current_user.trading_orders.maker.group_by(&:market)
    positions_scope = current_user.trading_orders.where.not(status: 'maker').order('id desc')
    @closed_positons = positions_scope.page(params[:closed_page]).per(10)
  end

  def show
    @market = @trading_order.market
    @market_outcome = @trading_order.market_outcome
    @contract = @trading_order.contract
  end

  def destroy
    # TODO: make sure funds are unescrowed, set flash message
    raise "something weird happened, trading order is not active maker order" unless @trading_order.maker?
    @trading_order.cancelled!
    redirect_back fallback_location: my_shares_path, notice: 'Order cancelled.'
  end

  private

    def init_trading_order
      @trading_order = current_user.trading_orders.findy(params[:id])
    end
end

app/controllers/my/trading_sets_controller.rb
class My::TradingSetsController < ApplicationController
  # TODO
  def show
    @market_shares_trx = current_user.market_shares_transactions.findy(params[:id])
    @market = @market_shares_trx.market
    @shares_transactions = current_user.spendable_shares.select { |trx| trx.market == @market }
  end
end

app/controllers/trading_orders_controller.rb
class TradingOrdersController < ApplicationController
  include My::SharesHistory
  before_action :market_outcome_init, only: %i[new create preview]
  before_action :trading_form_init, only: %i[new create preview]
  before_action :current_user_objects_init, only: %i[new create]

  skip_before_action :authenticate_user!, only: %i[new]

  respond_to :html, :js

  def create
    if @form.save
      msg = @form.order.active? ? 'The order has been created.' : 'The order has been created and closed immediately.'
      redirect_to my_trading_order_path(@form.order), notice: msg
    else
      render :new
    end
  end

  def preview
    @form.preview!
    render text: 'ok'
  end

  private

    # TODO: check when it's actually needed and split
    def market_outcome_init
      @market_outcome = MarketOutcome.findy(params[:market_outcome_id]) if params[:market_outcome_id]
      @market = @market_outcome.market
      check_if_tradeable!
      return unless @market_outcome
      @contract = @market_outcome.contracts.where(currency: params[:currency]).first
      @order_chart = order_chart if @contract
    end

    def check_if_tradeable!
      return unless @market
      return if @market_outcome.tradeable?
      # Market could be tradeable but contracts of this outcome could be non-active
      msg = @market.tradeable? ? 'Market is not tradeable.' : "Market is #{@market.state}."
      redirect_back fallback_location: markets_path, alert: msg
    end

    def reset_trading_order(**args)
      redirect_to new_market_outcome_trading_order_path(@market_outcome, @form.default_outcome_params), **args
    end

    def trading_form_init
      @form = TradingOrderForm.new(trading_order_form_params)
      reset_trading_order unless @form.valid_uri_params?
      @contract_quote = ContractQuote.new(@form.contract)
    end

    def trading_order_form_params
      uri_params = params.permit(TradingOrderForm.uri_params_keys)
      form_params = params.fetch(:trading_order_form, {}).permit(TradingOrderForm.form_attributes_keys)
      uri_params.merge(form_params).merge(user: current_user)
    end
end

app/views/my/trading_orders/_order.slim
.order-card
  section.order-card__header
    = link_to @market.title, market_path(@market)
  section.order-card__content-header
    h2
      = "#{@trading_order.order_type.titleize}: #{trading_order_human_state(@trading_order).titleize}"
  section.order-card__content
    = pmkt_table
      tr
        td.col-6 Operation
        td.col-6
          = trading_operation_badge(@trading_order.operation, classes: 'mr-2')
          = link_to @market_outcome.format_short_title, my_share_path(@trading_order.contract)
      tr
        td.col-6 Progress
        td.col-6= trading_order_progress(@trading_order)

      - case @trading_order.order_type
      - when 'market_order'
      - when 'limit_order'
        tr
          td.col-6
            - if @trading_order.bid?
              | Maximum price
            - else
              | Minimum price
          td.col-3
            = format_money(@trading_order.limit_price, currency: @trading_order.currency)
          td.col-3
            = format_odds(@trading_order.limit_odds)

      - unless @trading_order.trades.empty?
        tr
          td.col-6 Average price
          td.col-3= format_money(@trading_order.avg_price, currency: @trading_order.currency)
          td.col-3= format_odds(@trading_order.odds)

      tr
        td.col-6 Filled volume
        td.col-6= format_money(@trading_order.filled_amount, currency: @trading_order.currency, usd_rounding: 0.1)
      tr
        td.col-6 Filled shares
        td.col-6= @trading_order.filled_quantity
      tr
        td.col-6 Order created at
        td.col-6= format_secure_time(@trading_order.created_at)
  - if @trading_order.active?
    section.order-card__footer
      = cancel_trading_order_button(@trading_order, class: 'btn-action')

app/views/my/trading_orders/_trades.slim
// TODO: pagination
= ot_container('Trades')
  - if @trading_order.trades.empty?
    .pmkt-table-missing
      p There are no trades made for this order.
  - else
    = pmkt_table
      thead
        tr
          th.col-5 Date
          th.col-2 Price
          th.col-2 Shares
          th.col-3 Volume
      tbody
        - @trading_order.trades.each do |trade|
          tr
            td.col-5= format_secure_time(trade.created_at)
            td.col-2= format_odds(trade.odds)
            td.col-2= trade.quantity
            td.col-3= format_money(trade.amount, currency: trade.currency)

app/views/my/trading_orders/index.slim
= ot_container('My open orders') do
  - if @trading_orders.empty?
    .pmkt-table-missing
      p You do not have any open positions.
  - @trading_orders.each do |market, trading_orders|
    .orders-card
      .orders-card__header
        a data-toggle="collapse" data-parent="#market-orders-#{market.id}" href="#market-orders-#{market.id}" aria-expanded="true" class="collapse-indicator-after"
          = market.title
      .orders-card__content.collapse.show id="market-orders-#{market.id}"
        = pmkt_table
          thead.pmkt-md-up-block
            tr
              th.col-2 Time
              th.w-100
              th.col-1 Price
              th.col-2 Volume
              th.col-2 Progress
              th.col-2
          - trading_orders.each do |order|
            tr
              td.col-2.pmkt-md-up-flex= format_secure_time(order.created_at)
              td.w-100
                = trading_operation_badge(order.operation, classes: 'mr-2')
                = link_to order.market_outcome.format_short_title, my_trading_order_path(order)

              td.col-1.pmkt-md-up-flex= format_odds(order.odds)
              td.col-2.pmkt-md-up-flex= format_money(order.requested_amount, currency: order.currency, usd_rounding: 0.001)

              td.col-2.pmkt-md-up-flex= trading_order_progress(order)
              td.pmkt-table__action-cell
                = cancel_trading_order_button(order)

app/views/my/trading_orders/show.slim
= render 'order'
= render 'trades'
= render partial: 'markets/shared/market_comments'