config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'markets#index'
  # get 'theme', to: 'welcome#theme'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_for :admin_users, path: 'admin/profile', format: false, skip: [:registrations]

  resources :markets do
    member do
      get 'cover/*filename' => 'markets#cover', as: 'cover', format: false
    end
    collection do
      get 'watchlist/:list' => 'markets#watchlist', as: 'watchlist'
    end
    resources :market_outcomes, shallow: true
    resources :trading_sets, path: 'sets', shallow: true
  end

  resources :market_outcomes, path: 'outcomes' do
    resources :trading_orders, path: 'orders', shallow: true do
      collection do
        put 'preview'
        get 'help'
      end
    end
  end

  namespace :my do
    resources :funds do
      collection do
        match 'withdraw/:currency' => 'funds#withdraw', as: 'withdraw', via: %w[get post]
        get 'statement/:currency' => 'funds#statement', as: 'statement'
      end
    end

    resources :shares
    resources :trading_orders, path: 'orders'
    resources :trading_sets, path: 'sets'
    resources :referrals
  end

  get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
  get 'market/:id/:title' => 'markets#show', as: 'titled_market'

  get 'blog' => 'blog#index', as: 'blog'
  get 'blog/:id/*title' => 'blog#show', as: 'blog_post'
  post'blog/subscribe' => 'blog#subscribe', as: 'blog_subscribe'

  mount ApplicationApi, at: '/api/'

  admin_constraint = lambda do |request|
    admin = request.env['warden'].user(:admin_user)
    admin.is_a?(AdminUser) && admin.superadmin?
  end

  constraints admin_constraint do
    mount Resque::Server.new, at: '/admin/resque'
    namespace :admin do
      get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
      resources :markets do
        resources :market_outcomes
      end
    end
  end

  %w[about how terms fees security referral].each do |page|
    get page => "pages##{page}", as: page
  end
  get 'bounty' => redirect('/referral')
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :initialize_posts
  before_action :initialize_categories

  include BlogHelper

  BLOG_CONFIG = Rails.application.config_for(:blog).with_indifferent_access.freeze

  respond_to :html, :js

  def index
    @page_title = 'Blog'
    @sorted_posts = @post_configs.values.sort_by { |p| p['date'] }.reverse
  end

  def show
    @post_config = post_config(params[:id])
    if @post_config
      @page_title = @post_config[:title]
      redirect_to current_post_path unless valid_uri?
    else
      render status: 404, text: ''
    end
  end

  def subscribe
    @form = SubscribeForm.new(subscribe_form_params)
    @form.save
    render text: 'ok'
  end

  private

    def post_config(blog_id)
      post_config = BLOG_CONFIG[:posts][blog_id.to_i]
      return nil unless post_config
      post_config.merge(id: blog_id.to_i).with_indifferent_access
    end

    def valid_uri?
      params[:title] == blog_post_uri(@post_config)
    end

    def current_post_path
      blog_post_path_from_config(@post_config)
    end

    def initialize_posts
      @post_configs = BLOG_CONFIG[:posts].map { |k, v| [k, post_config(k)] }.to_h
    end

    def initialize_categories
      @ico_category = MarketCategory.where(name: 'ICOs').first
    end

    def subscribe_form_params
      params.fetch(:subscribe_form, {}).permit(:email)
    end
end

app/helpers/blog_helper.rb
module BlogHelper
  class MarkdownRenderer < Redcarpet::Render::HTML
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::UrlHelper
    include ActionView::Helpers::AssetTagHelper

    def link(link, title, content)
      link_to(content, link, title: title, rel: 'nofollow', target: '_blank', class: 'blog-link')
    end

    def image(link, title, alt_text)
      content_tag('a', image_tag(link, alt: alt_text || title, width: '100%'), href: link, class: 'md-zoomable-img')
    end
  end

  def blog_post_path_from_config(post_config)
    blog_post_path(post_config[:id], blog_post_uri(post_config))
  end

  def blog_post_url_from_config(post_config)
    blog_post_url(post_config[:id], blog_post_uri(post_config))
  end

  def blog_post_comment_url_from_config(post_config)
    blog_post_url(post_config[:id], 'post')
  end

  def blog_post_uri(post_config)
    post_config[:title].downcase.tr(' ', '-')
  end

  def blog_link_to(text, url)
    link_to(text, url, class: 'blog-link')
  end

  def blog_post_link_from_post_id(blog_post_id, args = {})
    post_config = @post_configs[blog_post_id]
    text = args[:text] || post_config[:title]
    css_class = args[:class] || 'btn-blog-action'
    link_to(text, blog_post_path_from_config(post_config), class: css_class)
  end
end

app/views/blog/posts/_1.slim
markdown:
  2018 kicked off with an immense interest in token-powered platforms and services, with sales of tokens generating [more than $4 billion](https://www.coinschedule.com/stats.html?year=2018) just in the first quarter.

  Public interest in Initial Coin Offerings is increasing rapidly, &mdash; as is the attention and scrutiny paid to scammers, untrustworthy companies, and faulty token models.

  ![Total volume of ICOs in 2018 Q1](/blog/1/icos2018q1.png)

  ## How risky are the ICOs?

  Unfortunately, startups with obscure whitepapers and non-viable business models still manage to get support from prestigious partners and lots of hype from their bounty programs.
  When news of their funding breaks, people are quick to roll their eyes and predict failure.
  And then, yes, almost half of them fail spectacularly.

  The graveyard of ICOs is littered with [dead tokens](https://bitcoinexchangeguide.com/deadcoins/), and they’re continuing to pile up at accelerated rate.

  Those who were shrewd enough to predict the failure had no way to act on, and benefit from, that knowledge. The ICO token market is *inefficient* but it isn’t *exploitable*.
  There is no way to make a profit just by predicting that a startup has a bad business model and that their tokens cost more than they should.

  A typical ICO token sale process lacks a certain type and direction of liquidity: you can’t short sell the newly issues tokens as they are not traded on any exchanges.

  > The graveyard of ICOs is littered with dead tokens, and they’re continuing to pile up at accelerated rate.

  ## Is it all that bad?

  Despite the risks posed by ICOs, we still believe that ICOs play an important role in accelerating innovation and can provide immense value in the future.
  The hope is not lost.

  The knowledge about scams and risky ICOs is out there, but until now there hasn’t been a way to act on it (and benefit).

  * Do you already know that an ICO is too risky?
  * Did you read the whitepaper and realised that the token-based service will never take off?

  Now you can make money from that.

  ## Introducing PredictionMarkt

  We value transparency in the blockchain space, and we want to contribute to the promotion of token-powered economic growth and consumer protection.
  To that end, we’ve created a platform that gathers the wisdom of the crowd to provide better insight into token value (&mdash; and ICO success).

  Through our platform, we’ve provided a market for you to make use of your insights about how startups will perform in their ICOs.

  Our #{blog_link_to "ICO prediction market category", browse_path(@ico_category)} is designed to inform investors, consumers, and regulators about important aspects of token projects.
  Available markets can range from the technical feasibility of the project and its roadmap to the fairness of token prices or even the trustworthiness and regulatory compliance of projects.

  On PredictionMarkt, you can take part in betting on markets such as:

  * “Will the team achieve their set milestones?”
  * “Will the token sale reach its market cap?”
  * “How fast will the tokens be sold out?”
  * “Will the average price of token X drop by Y% after a specified period?”, and so on.

  > Token sales are inefficient and lack a certain type and direction of liquidity: you can’t short sell the newly issues tokens.

  ## Sounds great, what's next?

  Are you ready to put your insights and intuition to work? Then PredictionMarkt is ready for you.

  Learn how trading works via our simple guide:

  #{blog_post_link_from_post_id(2, text: 'Learn to trade')}

  ## Tell us what you think!

    We believe that prediction markets will be an important tool for the blockchain space, and we can’t wait to hear your feedback about the service.

    Please reach out our #{blog_link_to 'telegram group', 'https://t.me/predictionmarkt'} or via #{mail_to 'concierge@predictionmarkt.com'} if you have any questions, comments, or feedback.

app/views/blog/posts/_2.slim
markdown:
  This post will guide you through 3 simple steps of buying shares in a prediction market.
  If you are new to prediction markets, you can read #{blog_link_to "how prediction markets work", how_path} first.

  ## Step 1

  First, create an account and deposit a bit of ETH you want to trade with.

  #{link_to "Sign Up", new_user_registration_path, class: 'btn-blog-action'}

  ## Step 2

  Find the market category you are interested in. There are a few #{blog_link_to "prediction market categories", markets_path} to choose from.

  Let’s take a look at the prediction market for SapienNetwork token, from the #{blog_link_to "prediction markets for initial coin offerings", browse_path(@ico_category)}.
  Normally the token being sold during the ICO is not openly tradeable, not everybody can participate in the crowd sale and it is not possible to short-sell the token (bet against the token price growth) before it gets listed on the exchanges.

  PredictionMarkt creates an opportunity to make money on that:

  ![Outcomes and their odds in the predction market](/blog/2/pmkt-sapien-network-token-odds.png)

  The crowd is ~70% confident that the SPN token price won't grow and it looks like the ICO might be risky.

  Let's say you know that the SPN token price will drop after the ICO, then you have two ways to profit from that:


  * Buy "No" shares at 70% of the price;
  * Purchase the fixed-price "Outcome Bundle" at 100% of the price, getting both "Yes" and "No" shares, then sell "Yes" shares immediately.

  If you are right, in both cases you will end up with "No" shares, which will be liquidated at 100% of the price when the market settles.

  ## Step 3

  Let’s try to purchase “No” shares:

  ![Purchase shares in the prediction market](/blog/2/pmkt-sapien-network-token-trade-no.png)

  You can see that the crowd is asking 70% price for the “No” shares. If you buy “No” shares for that price, you will get the other 30% when the token price drops in 3 months. Worth a shot!

  ## Done!

  ![Done, you've purchased shares in the prediction market](/blog/2/pmkt-sapien-network-token-order-complete.png)

  Now you own the "No" shares. You can sell them or trade them without waiting for the outcome of the events, otherwise the share will automatically convert to 100% if your prediction is correct.

  ## Reach out for help

  We just went through a simple trading example and PredictionMarkt enables you to utilise more powerful prediction trading strategies. We are always ready to help and we can’t wait to hear your feedback about the service. Please reach out our #{blog_link_to 'telegram group', 'https://t.me/predictionmarkt'} if you have any questions!