config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'markets#index'
  # get 'theme', to: 'welcome#theme'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_for :admin_users, path: 'admin/profile', format: false, skip: [:registrations]

  resources :markets do
    member do
      get 'cover/*filename' => 'markets#cover', as: 'cover', format: false
    end
    collection do
      get 'watchlist/:list' => 'markets#watchlist', as: 'watchlist'
    end
    resources :market_outcomes, shallow: true
    resources :trading_sets, path: 'sets', shallow: true
  end

  resources :market_outcomes, path: 'outcomes' do
    resources :trading_orders, path: 'orders', shallow: true do
      collection do
        put 'preview'
        get 'help'
      end
    end
  end

  namespace :my do
    resources :funds do
      collection do
        match 'withdraw/:currency' => 'funds#withdraw', as: 'withdraw', via: %w[get post]
        get 'statement/:currency' => 'funds#statement', as: 'statement'
      end
    end

    resources :shares
    resources :trading_orders, path: 'orders'
    resources :trading_sets, path: 'sets'
    resources :referrals
  end

  get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
  get 'market/:id/:title' => 'markets#show', as: 'titled_market'

  get 'blog' => 'blog#index', as: 'blog'
  get 'blog/:id/*title' => 'blog#show', as: 'blog_post'
  post'blog/subscribe' => 'blog#subscribe', as: 'blog_subscribe'

  mount ApplicationApi, at: '/api/'

  admin_constraint = lambda do |request|
    admin = request.env['warden'].user(:admin_user)
    admin.is_a?(AdminUser) && admin.superadmin?
  end

  constraints admin_constraint do
    mount Resque::Server.new, at: '/admin/resque'
    namespace :admin do
      get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
      resources :markets do
        resources :market_outcomes
      end
    end
  end

  %w[about how terms fees security referral].each do |page|
    get page => "pages##{page}", as: page
  end
  get 'bounty' => redirect('/referral')
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :initialize_posts
  before_action :initialize_categories

  include BlogHelper

  BLOG_CONFIG = Rails.application.config_for(:blog).with_indifferent_access.freeze

  respond_to :html, :js

  def index
    @page_title = 'Blog'
    @sorted_posts = @post_configs.values.sort_by { |p| p['date'] }.reverse
  end

  def show
    @post_config = post_config(params[:id])
    if @post_config
      @page_title = @post_config[:title]
      redirect_to current_post_path unless valid_uri?
    else
      render status: 404, text: ''
    end
  end

  def subscribe
    @form = SubscribeForm.new(subscribe_form_params)
    @form.save
    render text: 'ok'
  end

  private

    def post_config(blog_id)
      post_config = BLOG_CONFIG[:posts][blog_id.to_i]
      return nil unless post_config
      post_config.merge(id: blog_id.to_i).with_indifferent_access
    end

    def valid_uri?
      params[:title] == blog_post_uri(@post_config)
    end

    def current_post_path
      blog_post_path_from_config(@post_config)
    end

    def initialize_posts
      @post_configs = BLOG_CONFIG[:posts].map { |k, v| [k, post_config(k)] }.to_h
    end

    def initialize_categories
      @ico_category = MarketCategory.where(name: 'ICOs').first
    end

    def subscribe_form_params
      params.fetch(:subscribe_form, {}).permit(:email)
    end
end

app/helpers/blog_helper.rb
module BlogHelper
  class MarkdownRenderer < Redcarpet::Render::HTML
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::UrlHelper
    include ActionView::Helpers::AssetTagHelper

    def link(link, title, content)
      link_to(content, link, title: title, rel: 'nofollow', target: '_blank', class: 'blog-link')
    end

    def image(link, title, alt_text)
      content_tag('a', image_tag(link, alt: alt_text || title, width: '100%'), href: link, class: 'md-zoomable-img')
    end
  end

  def blog_post_path_from_config(post_config)
    blog_post_path(post_config[:id], blog_post_uri(post_config))
  end

  def blog_post_url_from_config(post_config)
    blog_post_url(post_config[:id], blog_post_uri(post_config))
  end

  def blog_post_comment_url_from_config(post_config)
    blog_post_url(post_config[:id], 'post')
  end

  def blog_post_uri(post_config)
    post_config[:title].downcase.tr(' ', '-')
  end

  def blog_link_to(text, url)
    link_to(text, url, class: 'blog-link')
  end

  def blog_post_link_from_post_id(blog_post_id, args = {})
    post_config = @post_configs[blog_post_id]
    text = args[:text] || post_config[:title]
    css_class = args[:class] || 'btn-blog-action'
    link_to(text, blog_post_path_from_config(post_config), class: css_class)
  end
end

app/views/blog/_post.slim
.blog-post
  h1
    = link_to post_config[:title], blog_post_path_from_config(post_config)
  = render "blog/posts/#{post_config[:id]}"

  .blog-post--footer
    = render partial: 'subscribe_form', locals: { post_config: @post_config }
    = social_links url: blog_post_url_from_config(post_config)

  .fb-comments data-href="#{blog_post_comment_url_from_config(post_config)}" data-numposts="5" data-width="100%" data-order-by="reverse_time"

app/views/blog/_subscribe_form.slim
.subscribe-form
  h2 Stay in the loop

  - if @form
    p
      | Thanks for subscribing! We'll keep you updated.
  - else
    p
      | Join our mailing list and stay up to date with the recent developments and news about prediction markets.

    = inline_simple_form_for(SubscribeForm.new, url: blog_subscribe_path, remote: true) do |f|
      = f.input :email, label: 'Your email address'
      = f.button :submit, 'Subscribe'

app/views/blog/index.slim
.blog-posts-list
  - @sorted_posts.each do |post_config|
    .blog-posts-list--item
      = render partial: 'post', locals: { post_config: post_config }

  = render file: 'pages/about'

app/views/blog/show.slim
= render partial: 'post', locals: { post_config: @post_config }

app/views/blog/subscribe.js.erb
$(".subscribe-form").html("<%= escape_javascript(render partial: 'subscribe_form') %>")