config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'markets#index'
  # get 'theme', to: 'welcome#theme'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_for :admin_users, path: 'admin/profile', format: false, skip: [:registrations]

  resources :markets do
    member do
      get 'cover/*filename' => 'markets#cover', as: 'cover', format: false
    end
    collection do
      get 'watchlist/:list' => 'markets#watchlist', as: 'watchlist'
    end
    resources :market_outcomes, shallow: true
    resources :trading_sets, path: 'sets', shallow: true
  end

  resources :market_outcomes, path: 'outcomes' do
    resources :trading_orders, path: 'orders', shallow: true do
      collection do
        put 'preview'
        get 'help'
      end
    end
  end

  namespace :my do
    resources :funds do
      collection do
        match 'withdraw/:currency' => 'funds#withdraw', as: 'withdraw', via: %w[get post]
        get 'statement/:currency' => 'funds#statement', as: 'statement'
      end
    end

    resources :shares
    resources :trading_orders, path: 'orders'
    resources :trading_sets, path: 'sets'
    resources :referrals
  end

  get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
  get 'market/:id/:title' => 'markets#show', as: 'titled_market'

  get 'blog' => 'blog#index', as: 'blog'
  get 'blog/:id/*title' => 'blog#show', as: 'blog_post'
  post'blog/subscribe' => 'blog#subscribe', as: 'blog_subscribe'

  mount ApplicationApi, at: '/api/'

  admin_constraint = lambda do |request|
    admin = request.env['warden'].user(:admin_user)
    admin.is_a?(AdminUser) && admin.superadmin?
  end

  constraints admin_constraint do
    mount Resque::Server.new, at: '/admin/resque'
    namespace :admin do
      get 'browse/:category_id/*name' => 'markets#index', as: 'market_category'
      resources :markets do
        resources :market_outcomes
      end
    end
  end

  %w[about how terms fees security referral].each do |page|
    get page => "pages##{page}", as: page
  end
  get 'bounty' => redirect('/referral')
end

app/controllers/admin/markets_controller.rb
module Admin
  class MarketsController < Admin::BaseController
    include MarketListable

    before_action :market_init
    before_action :market_outcome_init, only: %w[edit]

    def index
      super
      render 'markets/index'
    end

    def create
      if @market.save
        redirect_to edit_admin_market_path(@market)
      else
        render :new
      end
    end

    def update
      if @market.update_attributes(market_params)
        redirect_back fallback_location: edit_admin_market_path(@market), notice: "Market updated"
      else
        render :edit
      end
    end

    #
    # It needs to handle foreign constraints
    #
    # def destroy
    #   @market.destroy
    #   redirect_back fallback_location: admin_markets_path
    # end

    protected

      def visible_category_roots
        %w[Admin Generated Published]
      end

    private

      def market_init
        @market = params[:id] ? Market.findy(params[:id]) : current_user.markets.new(market_params)
      end

      def market_outcome_init
        @market_outcome = @market.market_outcomes.build
      end

      def market_params
        params.fetch(:market, {}).permit(:title, :lock_version,
                                         :ticker, :ticker_base,
                                         :rules, :close_date, :market_type, :state, :market_cover,
                                         market_category_ids: [])
      end
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  include MarketListable
  include My::SharesHistory
  include ReferralTrackable

  skip_before_action :authenticate_user!, only: %i[index show cover]
  before_action :find_viewable_market, only: %i[show cover]
  before_action :watchlist_markets_init, only: %i[watchlist]

  def watchlist
    render :index
  end

  def show
    @contracts = @market.contracts
    current_user_objects_init if current_user
  end

  def cover
    expires_in 30.days, public: true
    send_data(@market.market_cover_img_data, @market.market_cover_img_params.merge(disposition: 'inline'))
  end

  protected

    def visible_category_roots
      %w[Generated Published]
    end

  private

    def market_params
      params.fetch(:market, {})
    end

    def find_viewable_market
      @market = market_visible_scope.findy(params[:id])
      return if @market
      redirect_back fallback_location: markets_path, alert: 'Market not found'
    end

    def market_visible_scope
      current_admin_user ? Market : Market.user_viewable
    end

    def watchlist_markets_init
      case params[:list]
      when 'all'
        @markets = current_user.watched_markets
      when 'active'
        @markets = current_user.watched_markets_tradeable
      when 'closed'
        @markets = current_user.watched_markets_non_tradeable
      else
        redirect_back fallback_location: markets_path
      end
    end
end

app/helpers/market/navigation_helper.rb
module Market::NavigationHelper
  def nav_menu_link_groups
    @nav_menu_link_groups ||= nav_categories_groups + [nav_bottom_links]
  end

  def nav_chips_link_groups
    @nav_chips_link_groups ||= nav_categories_groups
  end

  def nav_categories_groups
    @nav_categories_groups ||= @nav_categories.map do |top_level_category, children|
      links = []
      links << watch_list_links if top_level_category.name == 'Generated'
      children.each do |category|
        category.self_and_descendants.each { |cat| links << nav_category_link(cat) }
      end
      links.compact
    end
  end

  # TODO: test
  def watch_list_links
    return nil unless current_user&.contract_transactions&.count&.positive?
    { name: 'Watch List',
      path: watchlist_markets_path(list: :all),
      active: params[:action] == 'watchlist',
      icon: '&#xE8F4;' }
  end

  # rubocop:disable Metrics/MethodLength
  def nav_bottom_links
    [
      { name: 'How it Works',
        path: how_path,
        active: params[:action] == 'how',
        icon: '&#xE8FD;' },
      { name: 'Blog',
        path: blog_path,
        active: params[:action] == 'blog',
        icon: '&#xE0E5;' },
      { name: 'About us',
        path: about_path,
        active: params[:action] == 'about',
        icon: '&#xE88E;' }
    ]
  end

  def nav_category_link(cat)
    return nil unless cat.visible || current_admin_user
    { name: cat.name,
      path: browse_path(cat),
      active: cat == @market_category,
      offset: cat.depth > 1,
      icon: cat.material_icon }
  end

  def nav_link_to(*args, &block)
    name = block_given? ? capture(&block) : args.shift
    url = url_for(args.shift || {})
    html_options = args.shift || {}
    a = { class: 'mdc-list-item', class_active: 'mdc-list-item--activated' }
    active_link_to name, url, html_options.merge(a)
  end

  def nav_menu_to(*args, &block)
    name = block_given? ? capture(&block) : args.shift
    url = url_for(args.shift || {})
    html_options = args.shift || {}
    a = { class: 'mdc-list-item', role: 'option', tabindex: 0 }
    a['aria-selected'] = true if html_options[:active]
    link = link_to(name, url)
    content_tag('li', link, a)
  end

  def browse_path(category)
    if category.admin? || params[:controller] == 'admin/markets'
      raise "non-admin user" unless current_admin_user
      admin_market_category_path(category, category.url_name)
    else
      market_category_path(category, category.url_name)
    end
  end

  def browse_url(category)
    market_category_url(category, category.url_name)
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
  def market_rules(market)
    if market.market_spec
      render partial: "markets/rules/#{market.market_spec.class.name.demodulize.underscore}"
    else
      sanitize_html(market.rules)
    end
  end

  def market_image_path(market)
    cover_market_path(market, market.market_cover_img_name) if market.display_market_cover?
  end

  def market_image_url(market)
    cover_market_url(market, market.market_cover_img_name) if market.display_market_cover?
  end

  def market_publishing_operations(market)
    return unless @market_category&.parent&.name == 'Publishing'
    capture do
      if @market_category.name == 'Pending'
        concat update_market_state_link(market, 'active')
        concat update_market_state_link(market, 'ignored')
      elsif @market_category.name == 'Ignored'
        concat update_market_state_link(market, 'active')
      end
    end
  end

  def market_settling_operations(market)
    return unless @market_category&.parent&.name == 'Settling'
    capture do
      if @market_category.name == 'Pending'
        concat update_market_state_link(market, 'settled') if market.winner_outcome
      end
    end
  end

  def update_market_state_link(market, state)
    url = admin_market_path(market, market: { state: state })
    name = state.capitalize + '!'
    link_to name, url, class: 'market-action-btn',
                       method: :put,
                       data: { confirm: 'Sure?' }
  end

  def set_winner_outcome_link(market, outcome)
    return if market.winner_outcome
    url = admin_market_market_outcome_path(market, outcome, market_outcome: { winner: true })
    name = 'winner!'
    link_to name, url, class: 'market-action-btn', method: :put, data: { confirm: 'Sure?' }
  end

  def market_outcome_odds_range(outcome)
    odds_list = outcome.odds_range.map do |o|
      number_with_precision(o * 100, precision: 0, strip_insignificant_zeros: true)
    end
    odds_list.uniq!
    content_tag(:span, odds_list.join(' – ') + '%', class: 'format-odds')
  end

  def market_outcome_bar(outcome, args = {})
    basis = outcome.odds_avg * 50
    basis = basis < 2 ? '2px' : "#{basis}%"
    icon = case outcome.odds_dir
           when 'up' # trending up
             "&#xE8E5;"
           when 'down'
             "&#xE8E3;"
           end

    bar = capture do
      concat content_tag(:div, '', class: 'outcome__bar--inner', style: "flex-basis: #{basis}")
      label_text = capture do
        concat content_tag(:i, icon.html_safe, class: 'material-icons') if icon
        concat content_tag(:span, outcome.format_short_title)
      end
      concat content_tag(:div, label_text, class: 'outcome__bar--label')
      concat content_tag(:div, market_outcome_odds_range(outcome), class: 'outcome__bar--value')
    end
    classes = ['market-outcome-bar']
    classes << args[:class] if args[:class]
    content_tag(:div, class: classes) do
      content_tag(:div, bar, class: 'outcome__bar')
    end
  end
end

app/views/markets/_info.slim
.card-block
  = pmkt_table
    tbody
      tr
        td.pmkt-table__key-cell
          | Market ticker
        td.w-100
          = @market.ticker
      - if @contract
        tr
          td.pmkt-table__key-cell
            | Contract ticker
          td.w-100
            = @contract.ticker
      - if @form
        tr
          td.pmkt-table__key-cell
            | Currency
          td.w-100
            = format_currency_name(@form.currency, code: true)
      tr
        td.pmkt-table__key-cell
          | Market type
        td.w-100.text-capitalize
          = @market.market_type
      tr
        td.pmkt-table__key-cell
          | Start date
        td.w-100
          = @market.start_date&.to_date || @market.created_at.to_date
      tr
        td.pmkt-table__key-cell
          | Close date
        td.w-100
          = @market.close_date&.to_date || "N/A"
  .pmkt-md-up-block
    = pmkt_table
      thead
        tr
          th.col-3 Currency
          th.col-3 Daily volume
          th.col-3 Market Cap
          th.col-3 Share Price
      tbody
        - @market.available_currencies.each do |currency|
          tr class=(@form&.currency == currency ? 'table-info' : nil)
            td.col-3
              = format_currency_name(currency)
            td.col-3
              = format_money(@market.prev_day_amount(currency), currency: currency, secure: true)
            td.col-3
              = format_money(@market.market_cap(currency), secure: true)
            td.col-3
              = format_money(@market.settle_price(currency), prepend: '0 — ', currency: currency)

app/views/markets/_market_outcomes.slim
= pmkt_table
  tbody
    - @market.market_outcomes.sort_by(&:odds_avg).reverse.each do |outcome|
      tr
        td.w-100
          = market_outcome_bar(outcome, class: 'market-outcome-bar--md')
        td.col-md-2.col-sm-6= trade_outcome_button(outcome)
    tr
      td.w-100
        span data={toggle: 'tooltip'} title='One share of each outcome'
          | Outcome Bundle
      td.col-md-2.col-sm-6= trade_set_button(@market)

.market-rules-shortdesc
  p = market_rules(@market)
  | When the market closes, shares for the correct prediction will be redeemed at 100% of the price, all the other shares will have no value.

app/views/markets/_markets_navigation.slim
= content_for :nav
  .layout-nav__column
    .mdc-drawer.mdc-drawer--permanent.mdc-typography
      .mdc-drawer__drawer
        nav.mdc-drawer__content.mdc-list
          - nav_menu_link_groups.each_with_index do |links, index|
            - links.each do |link|
              = nav_link_to link[:path], active: link[:active] do
                - if link[:icon]
                  i.material-icons.mdc-list-item__graphic aria-hidden="true"
                    == link[:icon]
                - if link[:offset]
                  = ("&nbsp;"*6).html_safe
                = link[:name]
            - if index < nav_menu_link_groups.size - 1
              hr.mdc-list-divider
          - admin_only do
            hr.mdc-list-divider
            = link_to 'Create', new_admin_market_path, class: 'btn-action'

  .layout-nav__row.container
    - if false
      - nav_chips_link_groups.each do |links|
        .layout-nav__row-group.mdc-chip-set.mdc-chip-set--choice
          - links.each do | link|
            - classes = ['mdc-chip', 'mdc-chip-set--choice']
            // TODO: mdc-chip--selected
            - classes << 'mdc-chip--activated' if link[:active]
            = link_to link[:path], class: 'layout-nav__row-group-link' do
              div class=classes
                - if link[:icon]
                  i.material-icons.mdc-chip__icon.mdc-chip__icon--leading== link[:icon]
                .mdc-chip__text
                  = link[:name]
              /= link_to link[:name], link[:path], class: 'mdc-chip__text'

    .mdc-select.mdc-select--box role="listbox"
      .mdc-select__surface tabindex="0"
        .mdc-select__label.mdc-select__label--float-above Category
        .mdc-select__selected-text
        .mdc-select__bottom-line
      .mdc-menu.mdc-select__menu
        ul.mdc-list.mdc-menu__items
          - nav_chips_link_groups.each_with_index do |links, index|
            - links.each do | link|
              = nav_menu_to link[:path], active: link[:active] do
                - if link[:offset]
                  = ("&nbsp;"*6).html_safe
                = link[:name]
            - if index < nav_chips_link_groups.size - 1
              .mdc-list-divider

app/views/markets/_orders.slim
.card-block
  - if orders.empty?
    .pmkt-table-missing
      p = empty_message
  - else
    = pmkt_table
      thead.pmkt-md-up-block
        tr
          th.w-100
          th.col-2 Price
          th.col-2 Volume
          th.col-2 Shares
          th.col-md-2.col-sm-6
      tbody
        - orders.each do |order|
          tr
            td.w-100
              = trading_operation_badge(order, classes: 'mr-2')
              // TODO: test
              = link_to order.market_outcome.format_short_title, my_trading_order_path(order)

            td.col-2.pmkt-md-up-flex= format_odds(order.odds)
            td.col-2.pmkt-md-up-flex= format_money(order.requested_amount, currency: order.currency, usd_rounding: 0.1)

            td.col-2.pmkt-md-up-flex= trading_order_progress(order, shares_only: true)
            td.pmkt-table__action-cell
              - if order.active?
                = cancel_trading_order_button(order)
              - else
                = trading_order_state(order, disabled: true)

app/views/markets/_rules.slim
.embedded-page-content

  h3 Outcome determination

  p= market_rules(@market)

  h3 Market liquidation

  p
    |
      Once the outcome is determined, the market closes for up to 48 hours during which it is possible to dispute the outcome.
      After that all the shares are liquidated and automatically converted to money.

  p
    |
      The liquidation value of the shares which represent the actual outcome of this market will be 100%.
      All the other shares will have no value.


  h3 Dispute rules

  p
    |
      Please contact #{ mail_to 'concierge@predictionmarkt.com' } for any disputes.

  p
    |
      The decisions and determinations about the market outcomes shall be at PredictionMarkt’s sole discretion and shall be final.

app/views/markets/_shares.slim
- if @shares_transactions.empty?
  .pmkt-table-missing
    p You don't own any shares in this market.
- else
  = pmkt_table
    thead.pmkt-md-up-block
      tr
        th.w-100
        th.col-2 Price
        th.col-2 Volume
        th.col-2 Shares
        th.col-md-2.col-sm-6
    tbody
      - @shares_transactions.each do |trx|
        tr
          td.w-100= link_to trx.market_outcome.format_short_title, my_share_path(trx.contract)
          - buy_odds = current_user.avg_buy_odds(trx.contract)
          - current_odds = trx.contract.quote.last_trade&.odds
          td.col-2.pmkt-md-up-flex= format_odds_compare(current_odds, buy_odds, detailed: true)
          td.col-2.pmkt-md-up-flex= shares_value(trx)
          td.col-2.pmkt-md-up-flex= trx.total
          td.pmkt-table__action-cell= trade_outcome_button(trx.market_outcome, currency: trx.contract.currency)

app/views/markets/edit.slim
= render partial: 'markets/shared/form', locals: { market: @market }

app/views/markets/index.slim
= render partial: 'markets/markets_navigation'
- if @markets.empty?
  .pmkt-table-missing-aligned
    p No markets.
- @markets.each do |market|
    .market-card
      .market-card__image.clickable style="background: url('#{market_image_path(market)}')" data-url=seo_market_path(market)
      .market-card__content-wrapper
        section.market-card__header
          = link_to market.title, seo_market_path(market)
        section.market-card__content
          section.market-card__outcomes
            - if market.winner_outcome

              h3.market-card__outcomes-winner
                i.material-icons &#xE5CA;
                = market.winner_outcome.format_short_title
              = "Market is #{market.state}."

            - else

              - market.market_outcomes.sort_by(&:odds_avg).reverse[0..1].each do |outcome|
                = market_outcome_bar(outcome)

          section.market-card-info
            .market-card-info__element
              - if market.close_date
                - if market.close_date < Time.current
                  - if market.tradeable?
                    | closes soon
                  - else
                    = "closed #{time_ago_in_words(market.close_date)} ago"
                - else
                  = "closes in #{time_ago_in_words(market.close_date)}"
              - else
                | n/a
              i.material-icons &#xE192;
            - if market.tradeable?
              - market.volumes(30.days.ago).each do |currency, amount|
                .market-card-info__element
                  = format_money(amount, currency: currency, secure: true, append: ' in 30d')
                  i.material-icons &#xE922;

        section.market-card__actions
          - if market.tradeable?
            = link_to 'Trade Predictions', seo_market_path(market), class: 'market-action-btn'
          - admin_only do
            = link_to 'Edit', edit_admin_market_path(market), class: 'market-action-btn'
            = market_publishing_operations(market)
            = market_settling_operations(market)
            span.market-card__actions-btn
              = market.state

app/views/markets/new.slim
= render partial: 'markets/shared/form', locals: { market: @market }

app/views/markets/show.slim
.market-headline
  .market-headline__cover style="background: url('#{market_image_path(@market)}')"
  .market-headline__title
    = page_headline(@market.title, no_wrapper: true)

= ot_tabs(social: true) do |c|
  - c.tab 'Outcomes'
    = render partial: 'market_outcomes'
  - c.tab 'Info'
    = render 'markets/info'
  - c.tab 'Rules'
    = render 'markets/rules'

- if current_user
  = ot_container('My shares')
    = render partial: 'shares'

  = ot_tabs do |c|
    - c.tab 'Open orders'
      = render partial: 'orders',
               locals: { orders: @trading_orders,
                         empty_message: "You don't have any open orders in this market." }

    - c.tab 'History'
      = render partial: 'orders',
               locals: { orders: @historical_orders,
                         empty_message: "The order history for this market is empty." }

= render partial: 'markets/shared/market_comments'